---
ID: "dd687b72-f15c-4eb0-b240-0cdd27c32121"
Parent: "75ba2247-c899-429a-9156-26dcbb08e261"
Template: "82c9a712-b590-4f6a-8f3e-b5d86daf49f9"
Path: /sitecore/client/Applications/Publishing/Common/System/ConfigurationItems/BorderFullRePublishSecurity
DB: core
SharedFields:
- ID: "8f10a590-4e67-4193-bad5-76c4aefcb5b2"
  Hint: RequiresRead
  Type: Checkbox
  Value: 1
- ID: "d4ad4def-8cfb-46d9-92b9-fb10d347b3b6"
  Hint: RequiresWrite
  Type: Checkbox
  Value: 1
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: |
    ar|sitecore\Sitecore Client Publishing|pe|-item:read|-item:write|pd|-item:read|-item:write|ar|sitecore\Sitecore Client Advanced Publishing|pe|+item:read|+item:write|pd|+item:read|+item:write|au|sitecore\advancedpublisher|pe|+item:read|+item:write|pd|+item:read|+item:write|ar|sitecore\Publishing Service Administrator|pe|+item:read|+item:write|pd|+item:read|+item:write|
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: BorderFullRePublishSecurity
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T140457Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: GrenzeVollständigeErneuteVeröffentlichungSicherheit
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T140502Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160317T113424Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 完全なリパブリッシュのセキュリティ
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T140505Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
