---
ID: "5a0b749e-a43e-4de6-9923-5c81964a8a07"
Parent: "75ba2247-c899-429a-9156-26dcbb08e261"
Template: "81f9fb86-7685-4fe6-a399-e62bbd2bfbca"
Path: /sitecore/client/Applications/Publishing/Common/System/ConfigurationItems/SearchConfigMessages
DB: core
SharedFields:
- ID: "3d2ac5ec-1035-4819-8df7-8da2b97d72aa"
  Hint: Root
  Value: "{0712A3D7-DA4A-4682-9BB9-8091962DB4CF}"
- ID: "f8a6a171-3688-4953-920e-8bb526541962"
  Hint: Template
  Value: "{87033790-C370-49F0-8B75-99C4A06A9901}"
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: SearchConfigMessages
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T140456Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: SucheConfigNachrichten
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T140501Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160226T072757Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 検索設定メッセージ
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161212T140504Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
